/**
 * Astro 5 Content Collections Configuration.
 *
 * Defines collections for the 20 GCD domain sites generated by the
 * Headless Contract Gateway (HCG). Each domain folder in src/content/
 * is a collection containing:
 *   - index.md       (domain overview page)
 *   - casepacks/*.md (per-casepack detail pages)
 *   - _data/*.json   (kernel snapshot — not collected, imported directly)
 */
import { defineCollection, z } from 'astro:content';
import { glob } from 'astro/loaders';

const domainSchema = z.object({
  title: z.string(),
  description: z.string().optional().default(''),
  domain: z.string().optional().default(''),
  lens: z.string().optional().default('Ontology'),
  regime: z.string().optional().default('UNKNOWN'),
  primaryColor: z.string().optional().default('#0f172a'),
  accentColor: z.string().optional().default('#f59e0b'),
  icon: z.string().optional().default('atom'),
  pageType: z.string().optional().default('domain'),
});

/**
 * Each domain folder is collected under a single "domains" collection.
 * The glob loader picks up all .md files across all 20 domain folders.
 */
const domains = defineCollection({
  loader: glob({ pattern: '*/index.md', base: './src/content' }),
  schema: domainSchema,
});

const casepacks = defineCollection({
  loader: glob({ pattern: '*/casepacks/*.md', base: './src/content' }),
  schema: z.object({
    title: z.string(),
    description: z.string().optional().default(''),
    pageType: z.string().optional().default('casepack'),
  }),
});

const networkIndex = defineCollection({
  loader: glob({ pattern: 'index.md', base: './src/content' }),
  schema: z.object({
    title: z.string(),
    description: z.string().optional().default(''),
    pageType: z.string().optional().default('index'),
  }),
});

export const collections = { domains, casepacks, networkIndex };
